/*Cursor que en un histórico con el nombre del libros, 
numero de ejemplares, numero de proveedores de ese libro, 
el precio mas bajo al que se ha comprado, el precio mas alto al que se ha comprado.
--EL PRECIO SOLO ESTA EN EL PRESTAMO VERDAD--ta dificil 
*/
DO $$
DECLARE
    bajo decimal := 0.0;
    alto decimal := 0.0;
	nproveedor int := 0;
	nejempl int;
	BOOKNAME VARCHAR;
    --Creación del cursor explicito
	C_EJEMPLARES CURSOR FOR SELECT * FROM EJEMPLAR;
	C_LIBROS CURSOR FOR SELECT * FROM LIBRO;

BEGIN
 FOR LIBRO IN C_LIBROS
 LOOP
 	NPROVEEDOR = 0;
    FOR EJEMPLAR IN C_EJEMPLARES 
        LOOP
            NPROVEEDOR = NPROVEEDOR + COUNT(PRO.ID_PROVEEDOR) FROM EJEMPLAR EJM 
			INNER JOIN RELATIONSHIP_7 R ON R.ID_EJEMPLAR = EJM.ID_EJEMPLAR
			INNER JOIN PROVEEDORES PRO ON PRO.ID_PROVEEDOR = R.ID_PROVEEDOR
			WHERE EJM.ID_EJEMPLAR = EJEMPLAR.ID_EJEMPLAR AND EJM.ID_LIBRO = LIBRO.ID_LIBRO;
			
		 END LOOP;
		 
		 SELECT MIN(PRECIO_VENTA) INTO BAJO FROM PROVEEDORES PRO 
			INNER JOIN RELATIONSHIP_7 R ON PRO.ID_PROVEEDOR = R.ID_PROVEEDOR 
			INNER JOIN EJEMPLAR EJM ON R.ID_EJEMPLAR = EJM.ID_EJEMPLAR
			WHERE EJM.ID_LIBRO = LIBRO.ID_LIBRO;
			
		SELECT MAX(PRECIO_VENTA) INTO ALTO FROM PROVEEDORES PRO 
			INNER JOIN RELATIONSHIP_7 R ON PRO.ID_PROVEEDOR = R.ID_PROVEEDOR 
			INNER JOIN EJEMPLAR EJM ON R.ID_EJEMPLAR = EJM.ID_EJEMPLAR
			WHERE EJM.ID_LIBRO = LIBRO.ID_LIBRO;
RAISE NOTICE 'NOMBRE: %        
PROVEEDORES: %  		N° DE EJEMPLARES: % 	PRECIO BAJO: % 		PRECIO ALTO: %', 
LIBRO.NOMBRE_LIBRO, NPROVEEDOR, LIBRO.NO_EJEMPLARES, BAJO, ALTO;
END LOOP;
END; 
$$ LANGUAGE 'plpgsql';
