/*Un procedimiento almacenado, reciba la CI de un cliente y me devuelva las variedades de libros que ha prestado y fecha.
*/
CREATE OR REPLACE FUNCTION LIBROS_PRESTADOS (VARCHAR) RETURNS SETOF VARCHAR
AS
$$ 

SELECT NOMBRE_LIBRO || '  ' || CAST(FECHA_PRESTAMO AS VARCHAR) FROM LIBRO L
INNER JOIN EJEMPLAR EJM ON L.ID_LIBRO = EJM.ID_LIBRO 
INNER JOIN PRESTAMO PRES ON PRES.ID_EJEMPLAR = EJM.ID_EJEMPLAR
INNER JOIN CLIENTE CLI ON CLI.ID_CLIENTE = PRES.ID_CLIENTE
WHERE
CI_CLIENTE = $1

$$
LANGUAGE SQL;

SELECT LIBROS_PRESTADOS('1351825487');
